describe('Testar formulario de cadastro de usuário', function() {
  it('Checar se a pagina existe', function() {
    cy.visit('http://localhost:8000')
  })

  it('testing fields required', function() {
    cy.get('input[name="name"]')
    cy.get('input[name="Address"]').type('rua vicentina maria freitas 112 ')
    cy.get('input[name="Neighborhood"]').type('Vila Santa Rita')
    cy.get('input[name="City"]').type('Belo Horizonte')
    cy.get('input[name="Country"]').type('Brasil')
    cy.get('input[name="email"]').type('flavialj@hotmail.com')
    cy.get('input[name="Age"]').type('25')
    cy.get('input[name="telephone"]').type('33369545')
    cy.get('#comments')
    cy.get('input[type="Submit"]').click()
  })
  it('testing if its on the same page', function() {
    cy.contains('Informations')
    cy.contains('name')
    cy.contains('Address')
    cy.contains('Neighborhood')
    cy.contains('City')
    cy.contains('Country')
    cy.contains('email Address')
    cy.contains('Age')
    cy.contains('telephone')
    cy.contains('comments')
  })
})
